// <auto-generated />
using System;
using ETicaretAspNetProje.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ETicaretAspNetProje.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    partial class ETicaretContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ETicaretAspNetProje.Models.Degerlendirme", b =>
                {
                    b.Property<string>("DegerlendirmeID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Puan")
                        .HasColumnType("float");

                    b.Property<string>("TedarikciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yorum")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("DegerlendirmeID");

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Kampanya", b =>
                {
                    b.Property<string>("KampanyaID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<double>("IndirimOrani")
                        .HasColumnType("float");

                    b.Property<string>("KampanyaAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuponKodu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KampanyaID");

                    b.ToTable("Kampanyalar");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Kategori", b =>
                {
                    b.Property<string>("KategoriId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AltKategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AnaKategoriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AraKategoriAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KategoriAciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KategoriId");

                    b.ToTable("Kategoriler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Musteri", b =>
                {
                    b.Property<string>("MusteriID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaAdresi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FaturaPostaKodu")
                        .HasColumnType("int");

                    b.Property<string>("FaturaSehri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KartAy")
                        .HasColumnType("int");

                    b.Property<string>("KartIsim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("KartNo")
                        .HasColumnType("bigint");

                    b.Property<string>("KartTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KartYil")
                        .HasColumnType("int");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriSoyadi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostaKodu")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("TCNo")
                        .HasColumnType("bigint");

                    b.Property<long>("Telno")
                        .HasColumnType("bigint");

                    b.HasKey("MusteriID");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.MusteriLog", b =>
                {
                    b.Property<string>("MusteriLogID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsleminYapildigiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilanIslem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MusteriLogID");

                    b.ToTable("MusteriLoglar");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Nakliyeci", b =>
                {
                    b.Property<string>("NakliyeciID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Faks")
                        .HasColumnType("bigint");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<long>("TelNo")
                        .HasColumnType("bigint");

                    b.HasKey("NakliyeciID");

                    b.ToTable("Nakliyeciler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Sehir", b =>
                {
                    b.Property<int>("SehirID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostaKodu")
                        .HasColumnType("int");

                    b.HasKey("SehirID");

                    b.ToTable("Sehirler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Siparis", b =>
                {
                    b.Property<string>("SiparisID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MusteriID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NakliyeciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostaKodu")
                        .HasColumnType("int");

                    b.Property<int>("SiparisNumarasi")
                        .HasColumnType("int");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TedarikciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TeslimTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("SiparisID");

                    b.ToTable("Siparisler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.SiparisDetay", b =>
                {
                    b.Property<string>("SiparisDetayID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<double>("Agırlık")
                        .HasColumnType("float");

                    b.Property<double>("BirimFiyat")
                        .HasColumnType("float");

                    b.Property<double>("BirimMiktar")
                        .HasColumnType("float");

                    b.Property<string>("Ebat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IslemTutari")
                        .HasColumnType("float");

                    b.Property<double>("KDVMiktar")
                        .HasColumnType("float");

                    b.Property<double>("KDVTutari")
                        .HasColumnType("float");

                    b.Property<int>("KartAy")
                        .HasColumnType("int");

                    b.Property<string>("KartIsim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("KartNo")
                        .HasColumnType("bigint");

                    b.Property<int>("KartYil")
                        .HasColumnType("int");

                    b.Property<string>("SiparisNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiparisDetayID");

                    b.ToTable("SiparisDetaylar");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.SiparisLog", b =>
                {
                    b.Property<string>("SiparisLogID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Il")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("IslemTutari")
                        .HasColumnType("float");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("MusteriID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiparisNumarasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SiparisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TedarikciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SiparisLogID");

                    b.ToTable("SiparisLoglar");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Tedarikci", b =>
                {
                    b.Property<string>("TedarikçiID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Faks")
                        .HasColumnType("bigint");

                    b.Property<string>("FaturaAdresi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaIlcesi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaSehri")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirmaYetkilisi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Kayittarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Logo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mahalle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeMetodlari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostaKodu")
                        .HasColumnType("int");

                    b.Property<string>("Sehir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("TelNo")
                        .HasColumnType("bigint");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WebSitesi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TedarikçiID");

                    b.ToTable("Tedarikciler");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.TedarikciLog", b =>
                {
                    b.Property<string>("TedarikciLogID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IslemTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("IsleminYapildigiIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TedarikciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YapilanIslem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TedarikciLogID");

                    b.ToTable("TedarikciLoglar");
                });

            modelBuilder.Entity("ETicaretAspNetProje.Models.Urun", b =>
                {
                    b.Property<string>("UrunID")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("BirimFiyat")
                        .HasColumnType("float");

                    b.Property<double>("BirimMiktar")
                        .HasColumnType("float");

                    b.Property<string>("Ebat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EklenmeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KategoriID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KdvMiktari")
                        .HasColumnType("float");

                    b.Property<string>("Renk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokDurumu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StokMiktari")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TedarikciID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAciklamasi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrunMarkasi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunID");

                    b.ToTable("Urunler");
                });
#pragma warning restore 612, 618
        }
    }
}
